[phases.setup]
    nixPkgs = ['nodejs', 'python3']
    aptPkgs = ['build-essential', 'libudev-dev']

[phases.build]
    cmds = ['pnpm install', 'pnpm build:workers']

[phases.start]
    cmd = 'pnpm start:prod:workers'

[build]
    nixpacksVersion = '1.21.0'