[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.dev"

[deploy]
startCommand = "pnpm run pm2"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
# Load production environment variables
envFile = ".env.production"