[phases.setup]
    nixPkgs = ['nodejs', 'python3']
    aptPkgs = ['build-essential', 'libudev-dev']

[phases.build]
    cmds = ['pnpm install', 'pnpm build:backend']

[phases.start]
    cmd = 'pnpm start:prod:backend'

[build]
    nixpacksVersion = '1.21.0'